// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34014
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ContactsContext.EventSourcing.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ContactProcessors")]
    [NUnit.Framework.CategoryAttribute("domain")]
    [NUnit.Framework.CategoryAttribute("contacts")]
    [NUnit.Framework.CategoryAttribute("commandprocessor")]
    [NUnit.Framework.CategoryAttribute("eventsourcing")]
    public partial class ContactProcessorsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ContactProcessors.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ContactProcessors", "Contact command processors specifications", ProgrammingLanguage.CSharp, new string[] {
                        "domain",
                        "contacts",
                        "commandprocessor",
                        "eventsourcing"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A create contact command raises a contact created and a contact title updated eve" +
            "nts")]
        [NUnit.Framework.TestCaseAttribute("{6010B03D-B110-42CA-87B1-0C6B926C6E4E}", "Iskander", "2", null)]
        [NUnit.Framework.TestCaseAttribute("{4573A8A5-6E33-4BFA-8F5F-4639AAF44A23}", "", "2", null)]
        public virtual void ACreateContactCommandRaisesAContactCreatedAndAContactTitleUpdatedEvents(string contactId, string title, string eventCount, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A create contact command raises a contact created and a contact title updated eve" +
                    "nts", exampleTags);
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("a contact command processor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.Given("a command processor context", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 11
 testRunner.And(string.Format("a create contact command is created with \"{0}\" and \"{1}\"", contactId, title), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.When("the create contact command processor processes the command", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
 testRunner.Then(string.Format("the command processor context has {0} emmitted events", eventCount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 14
 testRunner.And(string.Format("the command processor context has a contact created event as event 1 with \"{0}\"", contactId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And(string.Format("the command processor context has a contact title updated event as event 2 with \"" +
                        "{0}\" and \"{1}\"", contactId, title), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A update contact title command raises a contact title updated event")]
        [NUnit.Framework.TestCaseAttribute("{6010B03D-B110-42CA-87B1-0C6B926C6E4E}", "Hello", "1", null)]
        public virtual void AUpdateContactTitleCommandRaisesAContactTitleUpdatedEvent(string contactId, string title, string eventCount, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A update contact title command raises a contact title updated event", exampleTags);
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
 testRunner.Given("a contact command processor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 23
 testRunner.And("a command processor context", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.And(string.Format("a update contact title command is created with \"{0}\" and \"{1}\"", contactId, title), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.When("the update contact title command processor processes the command", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
 testRunner.Then(string.Format("the command processor context has {0} emmitted events", eventCount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 27
 testRunner.And(string.Format("the command processor context has a contact title updated event as event 1 with \"" +
                        "{0}\" and \"{1}\"", contactId, title), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A update contact picture command raises a contact picture updated event")]
        [NUnit.Framework.TestCaseAttribute("{6010B03D-B110-42CA-87B1-0C6B926C6E4E}", "{1811C884-0030-4F06-8FC0-2E6DCD28FD77}", "1", null)]
        public virtual void AUpdateContactPictureCommandRaisesAContactPictureUpdatedEvent(string contactId, string pictureId, string eventCount, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A update contact picture command raises a contact picture updated event", exampleTags);
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.Given("a contact command processor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 34
 testRunner.And("a command processor context", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
 testRunner.And(string.Format("a update contact picture command is created with \"{0}\" and \"{1}\"", contactId, pictureId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.When("the update contact picture command processor processes the command", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 37
 testRunner.Then(string.Format("the command processor context has {0} emmitted events", eventCount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 38
 testRunner.And(string.Format("the command processor context has a contact picture updated event as event 1 with" +
                        " \"{0}\" and \"{1}\"", contactId, pictureId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A clear contact picture command raises a contact picture cleared event")]
        [NUnit.Framework.TestCaseAttribute("{6010B03D-B110-42CA-87B1-0C6B926C6E4E}", "1", null)]
        public virtual void AClearContactPictureCommandRaisesAContactPictureClearedEvent(string contactId, string eventCount, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A clear contact picture command raises a contact picture cleared event", exampleTags);
#line 43
this.ScenarioSetup(scenarioInfo);
#line 44
 testRunner.Given("a contact command processor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 45
 testRunner.And("a command processor context", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.And(string.Format("a clear contact picture command is created with \"{0}\"", contactId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
 testRunner.When("the clear contact picture command processor processes the command", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 48
 testRunner.Then(string.Format("the command processor context has {0} emmitted events", eventCount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 49
 testRunner.And(string.Format("the command processor context has a contact picture cleared event as event 1 with" +
                        " \"{0}\"", contactId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
